services:
  - type: web
    name: inventario-pda
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn inventario_pda.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: inventario_pda.settings
      - key: SECRET_KEY
        value: django-insecure-xt^j-6-xm3umsrp_)=x%d7p)va*cbr%9i^p8+$bmjy83w2&g(d
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: '*'
